### ISSUE TITLE
Error: Cannot find module '/Users/macbook/node_code/node-radio-server/dist/index.js'

### ISSUE THREAD

**Issue by ramcona** [alexanderepolite/node-radio-server#1]
Hello you add command to run dist/index.js but no file for this

**Comment by ramcona** [comment]
Error: Cannot find module '/Users/macbook/node_code/node-radio-server/dist/index.js'

**Comment by AlexanderEpolite** [comment]
You need to install typescript and compile first, as outlined in the README:

> Compile: tsc (if you don't have this command, run `npm i -g typescript` to install it).

**Comment by ramcona** [comment]
oke, i do this and i have some error

src/index.ts:196:26 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(timeoutId: Timeout | undefined): void', gave the following error.
    Argument of type 'string | number | Timeout | undefined' is not assignable to parameter of type 'Timeout | undefined'.
      Type 'string' is not assignable to type 'Timeout'.
  Overload 2 of 2, '(id: number | undefined): void', gave the following error.
    Argument of type 'string | number | Timeout | undefined' is not assignable to parameter of type 'number | undefined'.
      Type 'string' is not assignable to type 'number'.

196             clearTimeout(timeout);
                             ~~~~~~~

**Comment by ramcona** [comment]
but when i run js its work. thank for make this project
